defaults:
  run:
    working-directory: ./policy/frontend
jobs:
  frontend:
    name: Build frontend
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - continue-on-error: true
      run: yarn install
    - continue-on-error: true
      run: yarn test
    - continue-on-error: true
      run: yarn build
name: Build frontend
on:
  repository_dispatch:
    types: trigger-ga___frontend.yml
