jobs:
  build:
    defaults:
      run:
        working-directory: android
    name: Gradle Checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Style
      run: ./gradlew checkStyle
    - continue-on-error: true
      name: Lint
      run: ./gradlew lint
    - continue-on-error: true
      name: Test
      run: ./gradlew test
    - continue-on-error: true
      name: Build
      run: ./gradlew build
    - continue-on-error: true
      name: Upload OpenBot App
      uses: actions/upload-artifact@v2
      with:
        name: robot-debug.apk
        path: android/robot/build/outputs/apk/debug/robot-debug.apk
    - continue-on-error: true
      name: Upload Controller App
      uses: actions/upload-artifact@v2
      with:
        name: controller-debug.apk
        path: android/controller/build/outputs/apk/debug/controller-debug.apk
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
