jobs:
  traffic:
    if: github.repository == 'isl-org/OpenBot'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download old traffic
      uses: dawidd6/action-download-artifact@v2
      with:
        name: traffic
        path: ./traffic/
        workflow: traffic.yml
        workflow_conclusion: success
    - continue-on-error: true
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.GH_TOKEN }}
      name: Get new traffic
      uses: sangonzal/repository-traffic-action@v0.1.4
    - continue-on-error: true
      name: Upload new traffic
      uses: actions/upload-artifact@v2
      with:
        name: traffic
        path: ./traffic/
on:
  repository_dispatch:
    types: trigger-ga___traffic.yml
